name: marcusneto
favicon: null
layout_spectrum: 0.12910603848285973
typography_spectrum: 0.14736454118974507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.75
  lightness: 0.21224231482483447
  saturation: 0.34689145628362894
  rhythmicContrast: 0.3118138015270233
purpose: []
